/**
 * email.ts — Resend email service
 *
 * Migrated from SendGrid to Resend.
 */

import { env } from '../env';
import { Resend } from 'resend';
import type { Report } from '../db/schema';

const resend = env.RESEND_API_KEY ? new Resend(env.RESEND_API_KEY) : null;

if (!resend) {
  console.warn('RESEND_API_KEY not found. Email notifications will be disabled.');
}

const FROM_EMAIL = env.RESEND_FROM_EMAIL || 'onboarding@resend.dev';
const ADMIN_EMAIL = env.ADMIN_EMAIL || 'moderncouture@icloud.com';

interface EmailParams {
  to: string;
  from?: string;
  subject: string;
  text?: string;
  html?: string;
}

export async function sendEmail(params: EmailParams): Promise<boolean> {
  if (!resend) {
    console.log('Email sending skipped — no RESEND_API_KEY configured');
    return false;
  }

  try {
    const { error } = await resend.emails.send({
      from: params.from || FROM_EMAIL,
      to: [params.to],
      subject: params.subject,
      text: params.text || '',
      html: params.html || '',
    });

    if (error) {
      console.error('Resend email error:', error);
      return false;
    }

    console.log(`Email sent successfully to ${params.to}`);
    return true;
  } catch (error) {
    console.error('Unexpected email error:', error);
    return false;
  }
}

export async function sendReportNotification(report: Report): Promise<boolean> {
  const reportTypeLabels: Record<string, string> = {
    inappropriate: 'Inappropriate Content',
    bug: 'Bug Report',
    feature_request: 'Feature Request',
    technical_issue: 'Technical Issue',
    content: 'Content Issue',
  };

  const priorityEmoji: Record<string, string> = {
    low: '🟢',
    medium: '🟡',
    high: '🟠',
    urgent: '🔴',
  };

  const reportTypeLabel = reportTypeLabels[report.reportType] || report.reportType;
  const priority = report.priority || 'medium';
  const deviceInfo = report.deviceInfo ? JSON.parse(report.deviceInfo) : null;

  const subject = `[${reportTypeLabel}] ${report.title} — ${priorityEmoji[priority] ?? ''} ${priority.toUpperCase()}`;

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 8px 8px 0 0;">
        <h1 style="margin: 0; font-size: 24px;">New Report Submitted</h1>
        <p style="margin: 10px 0 0 0; opacity: 0.9;">SymptomAnalyzer Diagnostic Application</p>
      </div>
      <div style="background: #f8f9fa; padding: 20px; border: 1px solid #dee2e6; border-top: none; border-radius: 0 0 8px 8px;">
        <div style="background: white; padding: 20px; border-radius: 6px; margin-bottom: 20px;">
          <h2 style="margin: 0 0 15px 0; color: #343a40;">${reportTypeLabel}</h2>
          <p><strong>Priority:</strong> ${priority.toUpperCase()}</p>
          <p><strong>Category:</strong> ${report.category || 'Not specified'}</p>
          <p><strong>Title:</strong> ${report.title}</p>
          <div style="background: #f8f9fa; padding: 15px; border-radius: 4px; white-space: pre-wrap;">${report.description}</div>
        </div>
        <div style="background: white; padding: 20px; border-radius: 6px; margin-bottom: 20px;">
          <h3 style="margin: 0 0 15px 0; color: #343a40;">User Information</h3>
          <p><strong>User ID:</strong> ${report.userId}</p>
          <p><strong>Email:</strong> ${report.userEmail || 'Not provided'}</p>
          ${report.relatedItemId ? `<p><strong>Related Item:</strong> ${report.relatedItemId}</p>` : ''}
        </div>
        ${deviceInfo ? `
        <div style="background: white; padding: 20px; border-radius: 6px; margin-bottom: 20px;">
          <h3 style="margin: 0 0 15px 0; color: #343a40;">Technical Information</h3>
          <p style="font-size: 12px; color: #6c757d;">
            <strong>User Agent:</strong> ${deviceInfo.userAgent || 'Unknown'}<br>
            <strong>Referrer:</strong> ${deviceInfo.referer || 'None'}<br>
            <strong>Timestamp:</strong> ${deviceInfo.timestamp || report.createdAt}
          </p>
        </div>` : ''}
        <div style="padding: 15px; background: #e9ecef; border-radius: 6px; text-align: center;">
          <p style="margin: 0; color: #6c757d; font-size: 12px;">
            Report #${report.id} — Auto-generated by SymptomAnalyzer
          </p>
        </div>
      </div>
    </div>
  `;

  const text = `
New Report: ${reportTypeLabel}
Title: ${report.title}
Priority: ${priority.toUpperCase()}
Category: ${report.category || 'Not specified'}

${report.description}

User ID: ${report.userId}
Email: ${report.userEmail || 'Not provided'}
Report #${report.id} | ${new Date(report.createdAt!).toLocaleString()}
  `;

  return sendEmail({ to: ADMIN_EMAIL, subject, text, html });
}
