import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import AssessmentForm from "@/components/assessment-form";
import { UsageBanner } from "@/components/UsageBanner";
import { PaymentModal } from "@/components/PaymentModal";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { History, Calendar, TrendingUp, Download, FileText, ChevronDown } from "lucide-react";
import type { Assessment as AssessmentType } from "@shared/schema";

export default function Assessment() {
  const [showHistory, setShowHistory] = useState(false);
  const [showPaymentModal, setShowPaymentModal] = useState(false);

  const { data: recentAssessments } = useQuery<AssessmentType[]>({
    queryKey: ["/api/assessments/recent"],
    enabled: showHistory,
  });

  const downloadHistoricalAssessment = (assessment: AssessmentType, format: 'txt' | 'html') => {
    const timestamp = new Date(assessment.createdAt).toLocaleString();
    const content = `
DIAGNOSTIC ASSESSMENT REPORT (Historical)
Original Assessment Date: ${timestamp}

RISK ASSESSMENT: ${assessment.riskLevel}
Total Score: ${assessment.totalScore}

SCORES: ${assessment.scores.join(', ')}

DIAGNOSTIC ANALYSIS:
${assessment.explanation}

${assessment.aiInsights ? `AI CLINICAL INSIGHTS:\n${assessment.aiInsights}\n` : ''}

${assessment.recommendations ? `RECOMMENDATIONS:\n${assessment.recommendations.map((rec, index) => `${index + 1}. ${rec}`).join('\n')}` : ''}

${assessment.confidence ? `AI Confidence: ${assessment.confidence}%` : ''}

---
This historical report was generated by the Diagnostic Assessment Tool
For medical decisions, please consult with a healthcare professional.
    `.trim();

    if (format === 'html') {
      const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <title>Historical Diagnostic Assessment Report</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; }
        .header { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
        .risk-badge { display: inline-block; padding: 5px 10px; border-radius: 5px; color: white; font-weight: bold; }
        .low-risk { background-color: #059669; }
        .moderate-risk { background-color: #d97706; }
        .high-risk { background-color: #dc2626; }
        .section { margin: 20px 0; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Historical Diagnostic Assessment Report</h1>
        <p>Original Assessment: ${timestamp}</p>
    </div>
    
    <div class="section">
        <h2>Risk Assessment</h2>
        <span class="risk-badge ${assessment.riskLevel ? assessment.riskLevel.toLowerCase().replace(' ', '-') : 'unknown'}">${assessment.riskLevel || 'Unknown'}</span>
        <p>Total Score: ${assessment.totalScore}</p>
        ${assessment.confidence ? `<p>AI Confidence: ${assessment.confidence}%</p>` : ''}
    </div>

    <div class="section">
        <h2>Assessment Scores</h2>
        <p>${assessment.scores.join(', ')}</p>
    </div>

    <div class="section">
        <h2>Diagnostic Analysis</h2>
        <p>${assessment.explanation}</p>
    </div>

    ${assessment.aiInsights ? `
    <div class="section">
        <h2>AI Clinical Insights</h2>
        <p>${assessment.aiInsights}</p>
    </div>
    ` : ''}

    ${assessment.recommendations ? `
    <div class="section">
        <h2>Recommendations</h2>
        <ol>
            ${assessment.recommendations.map(rec => `<li>${rec}</li>`).join('')}
        </ol>
    </div>
    ` : ''}

    <div class="footer">
        This historical report was generated by the Diagnostic Assessment Tool<br>
        For medical decisions, please consult with a healthcare professional.
    </div>
</body>
</html>
      `.trim();

      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `historical-assessment-${assessment.id}-${new Date(assessment.createdAt).toISOString().split('T')[0]}.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } else {
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `historical-assessment-${assessment.id}-${new Date(assessment.createdAt).toISOString().split('T')[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  };

  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
          Health Assessment
        </h1>
        <p className="text-gray-600 dark:text-gray-300">
          Complete your personalized health assessment to receive AI-powered insights
        </p>
      </div>

      <UsageBanner onUpgradeClick={() => setShowPaymentModal(true)} />

      <div className="space-y-8">
        <AssessmentForm />

        <PaymentModal 
          open={showPaymentModal} 
          onOpenChange={setShowPaymentModal} 
        />

        {showHistory && recentAssessments && recentAssessments.length > 0 && (
          <Card>
          <CardHeader className="bg-gradient-to-r from-indigo-600 to-indigo-700 text-white rounded-t-lg">
            <CardTitle className="text-xl flex items-center">
              <History className="mr-2 h-5 w-5" />
              Recent Assessment History
            </CardTitle>
            <p className="text-indigo-100 mt-1">Previous diagnostic analyses and results</p>
          </CardHeader>
          <CardContent className="p-6">
            <div className="space-y-4">
              {recentAssessments.map((assessment) => (
                <div key={assessment.id} className="border border-gray-200 rounded-lg p-4">
                  <div className="flex items-center justify-between mb-3">
                    <div className="flex items-center space-x-3">
                      <Calendar className="h-4 w-4 text-gray-500" />
                      <span className="text-sm text-gray-600">
                        {new Date(assessment.createdAt).toLocaleDateString()} at{' '}
                        {new Date(assessment.createdAt).toLocaleTimeString()}
                      </span>
                    </div>
                    <Badge 
                      className={`
                        ${assessment.riskLevel === 'Low Risk' ? 'bg-green-100 text-green-800' : ''}
                        ${assessment.riskLevel === 'Moderate Risk' ? 'bg-yellow-100 text-yellow-800' : ''}
                        ${assessment.riskLevel === 'High Risk' ? 'bg-red-100 text-red-800' : ''}
                      `}
                    >
                      {assessment.riskLevel}
                    </Badge>
                  </div>
                  
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-3">
                    <div className="text-center">
                      <div className="text-lg font-semibold text-primary">{assessment.totalScore}</div>
                      <div className="text-xs text-gray-500">Total Score</div>
                    </div>
                    {assessment.scores.map((score, index) => (
                      <div key={index} className="text-center">
                        <div className="text-lg font-semibold text-gray-700">{score}</div>
                        <div className="text-xs text-gray-500">Category {index + 1}</div>
                      </div>
                    ))}
                  </div>
                  
                  <p className="text-sm text-gray-700 line-clamp-2">{assessment.explanation}</p>
                  
                  <div className="mt-3 flex items-center justify-between">
                    {assessment.confidence && (
                      <div className="flex items-center text-xs text-gray-500">
                        <TrendingUp className="h-3 w-3 mr-1" />
                        {assessment.confidence}% AI Confidence
                      </div>
                    )}
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="outline" size="sm">
                          <Download className="mr-1 h-3 w-3" />
                          Download
                          <ChevronDown className="ml-1 h-3 w-3" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent>
                        <DropdownMenuItem onClick={() => downloadHistoricalAssessment(assessment, 'txt')}>
                          <FileText className="mr-2 h-4 w-4" />
                          Text File (.txt)
                        </DropdownMenuItem>
                        <DropdownMenuItem onClick={() => downloadHistoricalAssessment(assessment, 'html')}>
                          <Download className="mr-2 h-4 w-4" />
                          HTML Report (.html)
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
          </Card>
        )}
        
        <div className="text-center">
          <Button 
            variant="outline" 
            onClick={() => setShowHistory(!showHistory)}
            className="text-sm"
          >
            <History className="mr-2 h-4 w-4" />
            {showHistory ? 'Hide' : 'Show'} Assessment History
          </Button>
        </div>
      </div>
    </div>
  );
}
